package websocket

import (
	"math/rand"
	"time"
)

var playerIdList = []string{
	"James Peebles",
	"Michel Mayor",
	"Didier Queloz",
	"Arthur Ashkin",
	"Gérard Mourou",
	"Donna Strickland",
	"Rainer Weiss",
	"Barry C. Barish",
	"Kip S. Thorne",
	"David J. Thouless",
	"F. Duncan M. Haldane",
	"J. Michael Kosterlitz ",
	"Takaaki Kajita",
	"Arthur B. McDonald",
	"Isamu Akasaki",
	"Hiroshi Amano",
	"Shuji Nakamura",
	"François Englert",
	"Peter W. Higgs",
	"Serge Haroche",
	"David J. Wineland",
	"Saul Perlmutter",
	"Brian P. Schmidt",
	"Adam G. Riess",
	"Andre Geim",
	"Konstantin Novoselov",
	"Charles Kuen Kao",
	"Willard S. Boyle",
	"George E. Smith",
	"Yoichiro Nambu",
	"Makoto Kobayashi",
	"Toshihide Maskawa",
	"Albert Fert",
	"Peter Grünberg",
	"John C. Mather",
	"George F. Smoot",
	"Roy J. Glauber",
	"John L. Hall",
	"Theodor W. Hänsch",
	"David J. Gross",
	"H. David Politzer",
	"Frank Wilczek",
	"Alexei A. Abrikosov",
	"Vitaly L. Ginzburg",
	"Anthony J. Leggett",
	"Raymond Davis Jr.",
	"Masatoshi Koshiba",
	"Riccardo Giacconi",
	"Eric A. Cornell",
	"Wolfgang Ketterle",
	"Carl E. Wieman",
	"Zhores I. Alferov",
	"Herbert Kroemer",
	"Jack S. Kilby",
	"Gerardus ‘t Hooft",
	"Martinus J.G. Veltman",
	"Robert B. Laughlin",
	"Horst L. Störmer",
	"Daniel C. Tsui",
	"Steven Chu",
	"Claude Cohen-Tannoudji",
	"William D. Phillips",
	"David M. Lee",
	"Douglas D. Osheroff",
	"Robert C. Richardson",
	"Martin L. Perl",
	"Frederick Reines",
	"Bertram N. Brockhouse",
	"Clifford G. Shull",
	"Russell A. Hulse",
	"Joseph H. Taylor Jr.",
	"Georges Charpak",
	"Pierre-Gilles de Gennes",
	"Jerome I. Friedman",
	"Henry W. Kendall",
	"Richard E. Taylor",
	"Norman F. Ramsey",
	"Hans G. Dehmelt",
	"Wolfgang Paul",
	"Leon M. Lederman",
	"Melvin Schwartz",
	"Jack Steinberger ",
	"J. Georg Bednorz",
	"K. Alexander Müller",
	"Ernst Ruska",
	"Gerd Binnig",
	"Heinrich Rohrer",
	"Klaus von Klitzing",
	"Carlo Rubbia",
	"Simon van der Meer",
	"Subramanyan Chandrasekhar",
	"William Alfred Fowler",
	"Kenneth G. Wilson",
	"Nicolaas Bloembergen",
	"Arthur Leonard Schawlow",
	"Kai M. Siegbahn",
	"James Watson Cronin",
	"Val Logsdon Fitch",
	"Sheldon Lee Glashow",
	"Abdus Salam",
	"Steven Weinberg",
	"Pyotr Leonidovich Kapitsa",
	"Arno Allan Penzias",
	"Robert Woodrow Wilson",
	"Philip Warren Anderson",
	"Sir Nevill Francis Mott",
	"John Hasbrouck van Vleck",
	"Burton Richter",
	"Samuel Chao Chung Ting",
	"Aage Niels Bohr",
	"Ben Roy Mottelson",
	"Leo James Rainwater",
	"Sir Martin Ryle",
	"Antony Hewish",
	"Leo Esaki",
	"Ivar Giaever",
	"Brian David Josephson",
	"John Bardeen",
	"Leon Neil Cooper",
	"John Robert Schrieffer",
	"Dennis Gabor",
	"Hannes Olof Gösta Alfvén",
	"Louis Eugène Félix Néel",
	"Murray Gell-Mann",
	"Luis Walter Alvarez",
	"Hans Albrecht Bethe",
	"Alfred Kastler",
	"Sin-Itiro Tomonaga",
	"Julian Schwinger",
	"Richard P. Feynman",
	"Charles Hard Townes",
	"Nicolay Gennadiyevich Basov",
	"Aleksandr Mikhailovich Prokhorov",
	"Eugene Paul Wigner",
	"Maria Goeppert Mayer",
	"J. Hans D. Jensen",
	"Lev Davidovich Landau",
	"Robert Hofstadter",
	"Rudolf Ludwig Mössbauer",
	"Donald Arthur Glaser",
	"Emilio Gino Segrè",
	"Owen Chamberlain",
	"Pavel Alekseyevich Cherenkov",
	"Il´ja Mikhailovich Frank",
	"Igor Yevgenyevich Tamm",
	"Chen Ning Yang",
	"Tsung-Dao (T.D.) Lee",
	"William Bradford Shockley",
	"John Bardeen",
	"Walter Houser Brattain",
	"Willis Eugene Lamb",
	"Polykarp Kusch",
	"Max Born",
	"Walther Bothe",
	"Frits Zernike",
	"Felix Bloch",
	"Edward Mills Purcell",
	"Sir John Douglas Cockcroft",
	"Ernest Thomas Sinton Walton ",
	"Cecil Frank Powell",
	"Hideki Yukawa ",
	"Patrick Maynard Stuart Blackett",
	"Sir Edward Victor Appleton",
	"Percy Williams Bridgman",
	"Wolfgang Pauli ",
	"Isidor Isaac Rabi",
	"Otto Stern",
	"Ernest Orlando Lawrence",
	"Enrico Fermi",
	"Clinton Joseph Davisson",
	"George Paget Thomson",
	"Victor Franz Hess",
	"Carl David Anderson",
	"James Chadwick",
	"Erwin Schrödinger",
	"Paul Adrien Maurice Dirac",
	"Werner Karl Heisenberg",
	"Sir Chandrasekhara Venkata Raman",
	"Prince Louis-Victor Pierre Raymond de Broglie",
	"Owen Willans Richardson",
	"Arthur Holly Compton",
	"Charles Thomson Rees Wilson",
	"Jean Baptiste Perrin",
	"James Franck",
	"Gustav Ludwig Hertz",
	"Karl Manne Georg Siegbahn",
	"Robert Andrews Millikan",
	"Niels Henrik David Bohr",
	"Albert Einstein",
	"Charles Edouard Guillaume",
	"Johannes Stark",
	"Max Karl Ernst Ludwig Planck",
	"Charles Glover Barkla",
	"Sir William Henry Bragg",
	"William Lawrence Bragg",
	"Max von Laue",
	"Heike Kamerlingh Onnes",
	"Nils Gustaf Dalén",
	"Wilhelm Wien",
	"Johannes Diderik van der Waals",
	"Guglielmo Marconi",
	"Karl Ferdinand Braun",
	"Gabriel Lippmann",
	"Albert Abraham Michelson",
	"Joseph John Thomson",
	"Philipp Eduard Anton von Lenard",
	"Lord Rayleigh (John William Strutt)",
	"Antoine Henri Becquerel",
	"Pierre Curie",
	"Marie Curie, née Sklodowska",
	"Hendrik Antoon Lorentz",
	"Pieter Zeeman",
	"Wilhelm Conrad Röntgen",
}

var playerIdUsed = make(map[string]bool)

func initPlayerIds() {
	for _, playerId := range playerIdList {
		playerIdUsed[playerId] = false
	}
}

func createPlayerId() (playerId string) {
	rand.Seed(time.Now().UnixNano())
	playerId = playerIdList[rand.Intn(len(playerIdList))]
	for playerIdUsed[playerId] {
		playerId = playerIdList[rand.Intn(len(playerIdList))]
	}
	playerIdUsed[playerId] = true
	return
}
